### ISSUE TITLE
create_directory () failed on Network share using UNC paths

### ISSUE THREAD

**Issue by rap2021** [UbiCastTeam/mkvtoolnix-ubicast#1]
I believe this started on 74.0.0.   I've always muxed onto UNC shares with no problems.  I updated more recently for other reasons and now I can no longer mux over network -only on the local machine.  Full error is:

> _The file '\\SERVER\Movies EIGHT\Diner - 1982\Diner.1982.BluRay.1080p.X264-RAP.mkv' could not be opened for writing: create_directory() failed._

BTW - tried in on a few other "\\SERVER" drives... same problem.

**Comment by rap2021** [comment]
BTW - this project tool is truncating the first "back-slash" before "SERVER" , in the file path name.

**Comment by fthiery** [comment]
Hi there, for the record this is not the upstream project, and we are not using this project anymore (i'll archive it). You probably want to use the upstream project here: https://gitlab.com/mbunkus/mkvtoolnix

Regards,
